version: "3"

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile_server
    ports:
      - "5000:5000"
    environment:
      - PYTHONUNBUFFERED=0
  client_1:
    build:
      context: .
      dockerfile: Dockerfile_client
    ports:
      - "5001:5001"
    environment:
      - USERNAME=Alice
      - ECHOSRV_HOST=server
      - ECHOSRV_PORT=5000
      - PYTHONUNBUFFERED=0
    depends_on:
      - server
  client_2:
    build:
      context: .
      dockerfile: Dockerfile_client
    ports:
      - "5002:5002"
    environment:
      - USERNAME=Bob
      - ECHOSRV_HOST=server
      - ECHOSRV_PORT=5000
      - PYTHONUNBUFFERED=0
    depends_on:
      - server
