FROM threeheadedknight/docker-grpc-python3:latest

WORKDIR /app

COPY /requirements.txt /app
RUN pip install -r requirements.txt

COPY /server_example /app
COPY /proto /app/proto

RUN cd /app/proto && \
    chmod +x generate_protobufs.sh && \
    ./generate_protobufs.sh

CMD ["python", "-u", "server.py"]
